### ISSUE TITLE
Assess RxJava execution strategy

### ISSUE THREAD

**Issue by trioletas** [ctco-dev/spring-boot-graphql-template#8]
https://github.com/nfl/graphql-rxjava

**Comment by MichiruKayo** [comment]
Not possible, this library is outdated (2years old) and is not compatible with latest versions of graphql.
There is 1 fork from tibor-kocsis that supports graphql 3.0 v , but we have 4.x and is latest is 5.x ...

**Comment by trioletas** [comment]
Thanks for looking into this.
